name: toronto-shared-bike-oracle

volumes:
  oracledata:
  # oraclebackup:

networks:
  public-net:
    driver: bridge

services:
  oracle19cDB:
    container_name: oracle19cDB
    image: simonangelfong/oracledb19c:1.0
    restart: unless-stopped
    environment:
      ORACLE_SID: ${ORACLE_SID:-ORCLCDB}
      ORACLE_PDB: ${ORACLE_PDB:-pdb1}
      ORACLE_PWD: ${ORACLE_PWD:-SecurePassword123}
    volumes:
      - ./scripts:/opt/oracle/scripts/ # scripts
      - ../data:/data # source data
      - ../export:/export # export data
      - oracledata:/opt/oracle/oradata # persist data
      # - oraclebackup:/opt/oracle/fast_recovery_area # backup
    networks:
      - public-net # public for dev
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "/opt/oracle/scripts/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 2m
    
